### ISSUE TITLE
Typo on dateformat.io website

### ISSUE THREAD

**Issue by chin8628** [jonstuebe/date-time-generator#1]
The example of Day of month is wrong. The first example of day of month should be '2 digits without leading zeros'

![image](https://user-images.githubusercontent.com/2943187/34082358-1ece5390-e38f-11e7-986c-a4fc816e02dc.png)

**Comment by jonstuebe** [comment]
this has been fixed. I've also updated the repo to support https (which will take 24 hours to go into effect) and upgrade all packages including react to version 16.
